Promise.resolve(10).then((x) => Promise.resolve(x * 2)).catch((e) => console.log('rejected', e))